### ISSUE TITLE
getRandomBigNumber Isn't Evenly Distributed

### ISSUE THREAD

**Issue by brianoctan** [victorqribeiro/googol#1]
Appreciate the project; something to take note:

The length of digits generated via
`	const r = Math.floor(Math.random() * 101);`
is not evenly distributed.

Consider a number with a max of 2 digits (instead of a googol). 
Numbers 0-9 will have a 50% chance to be chosen as would numbers 10-99.

A solution would be to always generate a fixed length of digits, then remove any preceding zeros.

[Link to HN Discussion](https://news.ycombinator.com/item?id=21732389)

**Comment by victorqribeiro** [comment]
Is kind hard for me to even calculate the probabilities of such large numbers, but, in order for me to get a number with, lets say 10 decimal places using your proposed solution, I would have to get 90 consecutive leading zeros. Seems to me that would never happen.
